table Fact_Std_Cost
	lineageTag: 2743da03-023f-5278-9c94-e54222d2ab7e

	column Material_Id
		dataType: string
		lineageTag: eaa35f2e-a24f-513f-bb8f-38b0c967ec35
		summarizeBy: none
		sourceColumn: Material_Id

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 0ab12f10-8241-53a0-9941-e53e855b335d
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5447f75b-111a-55eb-9a53-6e3bf1289651
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Std_Cost_USD_per_kg
		dataType: double
		lineageTag: 0017c390-73a5-5859-b85b-717ca95002b8
		summarizeBy: none
		sourceColumn: Std_Cost_USD_per_kg

		annotation SummarizationSetBy = Automatic

	partition Fact_Std_Cost = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Fact_Std_Cost.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Material_Id", type text}, {"Plant", type text}, {"Year", Int64.Type}, {"Std_Cost_USD_per_kg", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
