table Dim_Year
	lineageTag: 336f834e-5749-50f4-984c-0e4c52a72970

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fe38ad67-4992-51b4-96b0-53118c4b3fb6
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Is_Milestone
		dataType: boolean
		lineageTag: 16e62157-9037-5a72-af1b-d3adb0460745
		summarizeBy: none
		sourceColumn: Is_Milestone

		annotation SummarizationSetBy = Automatic

	partition Dim_Year = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Dim_Year.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Year", Int64.Type}, {"Is_Milestone", type logical}}, "en-US"),
				    Result = Typed
				in
				    Result

	annotation PBI_ResultType = Table
